/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PerformaceRouteImport } from './routes/performace'
import { Route as LiveFeedRouteImport } from './routes/live-feed'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminNewEntryRouteImport } from './routes/_admin.new-entry'
import { Route as AdminEditEntryIdRouteImport } from './routes/_admin.edit-entry.$id'

const PerformaceRoute = PerformaceRouteImport.update({
  id: '/performace',
  path: '/performace',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveFeedRoute = LiveFeedRouteImport.update({
  id: '/live-feed',
  path: '/live-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNewEntryRoute = AdminNewEntryRouteImport.update({
  id: '/new-entry',
  path: '/new-entry',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditEntryIdRoute = AdminEditEntryIdRouteImport.update({
  id: '/edit-entry/$id',
  path: '/edit-entry/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/live-feed': typeof LiveFeedRoute
  '/performace': typeof PerformaceRoute
  '/new-entry': typeof AdminNewEntryRoute
  '/edit-entry/$id': typeof AdminEditEntryIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/live-feed': typeof LiveFeedRoute
  '/performace': typeof PerformaceRoute
  '/new-entry': typeof AdminNewEntryRoute
  '/edit-entry/$id': typeof AdminEditEntryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/ledger': typeof LedgerRoute
  '/live-feed': typeof LiveFeedRoute
  '/performace': typeof PerformaceRoute
  '/_admin/new-entry': typeof AdminNewEntryRoute
  '/_admin/edit-entry/$id': typeof AdminEditEntryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/ledger'
    | '/live-feed'
    | '/performace'
    | '/new-entry'
    | '/edit-entry/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/ledger'
    | '/live-feed'
    | '/performace'
    | '/new-entry'
    | '/edit-entry/$id'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/dashboard'
    | '/ledger'
    | '/live-feed'
    | '/performace'
    | '/_admin/new-entry'
    | '/_admin/edit-entry/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  LedgerRoute: typeof LedgerRoute
  LiveFeedRoute: typeof LiveFeedRoute
  PerformaceRoute: typeof PerformaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/performace': {
      id: '/performace'
      path: '/performace'
      fullPath: '/performace'
      preLoaderRoute: typeof PerformaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live-feed': {
      id: '/live-feed'
      path: '/live-feed'
      fullPath: '/live-feed'
      preLoaderRoute: typeof LiveFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/new-entry': {
      id: '/_admin/new-entry'
      path: '/new-entry'
      fullPath: '/new-entry'
      preLoaderRoute: typeof AdminNewEntryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/edit-entry/$id': {
      id: '/_admin/edit-entry/$id'
      path: '/edit-entry/$id'
      fullPath: '/edit-entry/$id'
      preLoaderRoute: typeof AdminEditEntryIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminNewEntryRoute: typeof AdminNewEntryRoute
  AdminEditEntryIdRoute: typeof AdminEditEntryIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminNewEntryRoute: AdminNewEntryRoute,
  AdminEditEntryIdRoute: AdminEditEntryIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRoute,
  LedgerRoute: LedgerRoute,
  LiveFeedRoute: LiveFeedRoute,
  PerformaceRoute: PerformaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
